### ISSUE TITLE
Conda/Mamba migrated to a new init system

### ISSUE THREAD

**Issue by jmuchovej** [OldGrumpyViking/hatch-conda#1]
A few years ago, `conda`/`mamba` moved to "requiring" `[conda|mamba] init` before being able to use `[conda|mamba] activate <env_name>`. I've generally found that just doing something like the following is sufficient to remove the warning and ensure that `[conda|mamba] activate <env_name>` works like a charm.

```shell
source <conda_path>/etc/profile.d/conda.sh  # For `conda`
source <conda_path>/etc/profile.d/mamba.sh  # For `mamba` – you also need the `conda` one too.
```

https://github.com/OldGrumpyViking/hatch-conda/blob/99e0dded8785ffbacc358f2ef3ef1205411a6c63/hatch_conda/plugin.py#L154-L158

I just started using `hatch`, so I'm not super familiar with the plugin system, but I _think_ I'd be willing to submit a PR if needed.

**Comment by harelwa** [comment]
@jmuchovej i think it's a fair assumption you have conda properly setup, and this also means you have initialized it. i would not mess with that assumption. what do you think @OldGrumpyViking ?

**Comment by OldGrumpyViking** [comment]
Hi the init command is for setting your terminal up. When using hatch and hatch-conda it is assumed that your terminal is properly setup as @harelwa mentioned.

This will not be something that will be done automatically by the plugin as it messes with the system files.

From the [conda docs](https://docs.conda.io/projects/conda/en/latest/commands/init.html):

> This command makes changes to your system that are specific and customized for each shell. To see the specific files and locations on your system that will be affected before, use the '--dry-run' flag. To see the exact changes that are being or will be made to each location, use the '--verbose' flag.

> IMPORTANT: After running conda init, most shells will need to be closed and restarted for changes to take effect.
