### ISSUE TITLE
not sure how `hatch env create` is supposed to work? 

### ISSUE THREAD

**Issue by jgunstone** [OldGrumpyViking/hatch-conda#3]
Hi there, 

I've got a project where I've add the following to the `pyproject.toml`: 

```toml
[tool.hatch.envs.ipyautoui-dev]
type = "conda"
command = "mamba"
```

on the command line, in a mamba env with `hatch`, `hatch-conda` installed, i run: 

`hatch env create`

and then run: 

![image](https://user-images.githubusercontent.com/21370980/197241250-43fc3899-ca9d-4fa7-b89d-b443531c9d54.png)

within the `conda list` my env packages are not present. 

also the conda env doesn't exist:
![image](https://user-images.githubusercontent.com/21370980/197241582-fb45e8b5-cdaf-42c6-84ce-00bc2a6f6c25.png)

if i `pip list` then the packages are present. 

what is happening? 
I guess I assumed that hatch would make a conda environment but that is obv not happening... could you explain?

many thanks

**Comment by OldGrumpyViking** [comment]
In your `pyproject.toml` you have called your environment `ipyautoui-dev`.

When calling hatch you have to specify this environment to use it otherwize hatch will use the default environment.

Please refer to the [Hatch documentation](https://hatch.pypa.io/latest/environment/#environments).

There is a known bug #1 that the `hatch shell` command is not working for the conda environments.

However you should be able to use your specified environment using the `run` command.
(Note: You do not have to create the environment before using it, as hatch will do this automatically.)

The following commands should install your conda environment and list it.
The pip list command will list the installed packages in the environment.
The mamba env list will then show the created conda environment.

```console
$ hatch run ipyautoui-dev:pip list
$ mamba env list
```
