### ISSUE TITLE
Is it possible to use prefix environments instead of named environments?

### ISSUE THREAD

**Issue by indigoviolet** [OldGrumpyViking/hatch-conda#4]
The equivalent of `conda create -p ./.venv`?

**Comment by harelwa** [comment]
@indigoviolet @OldGrumpyViking  

is this still relevant ? it's currently not implemented, but if you peek inside the plugin, you'll see it should be fairly easy to add.

**Comment by dimazest** [comment]
I was looking for similar functionality and indeed it should be relatively easy to pass the `-p` flag when an environment is created.

Btw, I tried to specify `path: .venv/` in `environment.yml`, but it doesn't seem to work.
